#!/usr/bin/env bash
# Connect to the server using the private key ~/.ssh/school with the user ubuntu

ssh -i ~/.ssh/school ubuntu@184.73.104.7
#key fingerprint = vNDRKI3rCq56ii5eZwJwz467F3+7Gjnkm2RorBVCqUg